backend:
  name: git-gateway
  branch: main # or master, depending on your default GitHub branch

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "catalog"
    label: "Catalog Products"
    folder: "content/products"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Video", name: "video", widget: "file", required: false }
